server:
  port: 8080
spring:
  application:
    name: DynamicDataSource
  main:
    # 设置定义 bean 可以被覆盖（多数源需要）
    allow-bean-definition-overriding: true

  # 数据源配置，数据从 common 文件提取
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${public.spring.datasource.host}:${public.spring.datasource.port}/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: ${public.spring.datasource.username}
    password: ${public.spring.datasource.password}

    #driver-class-name:springBoot2.x 后驱动程序通过SPI自动注册，并且通常不需要手动加载驱动程序类。
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initial-size: 5   #线程池初大小
      min-idle: 5       #线程池最小空闲连接
      max-active: 2000  #线程池最大连接数
      # 配置获取连接等待超时的时间
      max-wait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      # SpringBoot 2.x 此处记得去掉 log4j
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: toor
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式，一定要加上 ""，否则会报错
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

# Swagger 开关，true：开/false：关
swagger:
  enable: true

# 开启 mybatis 查询日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 多数据源配置，需要一个默认数据源
db:
  # 默认连接的数据源
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接前缀
    url-base: jdbc:mysql://
    host: ${public.spring.datasource.host}
    port: ${public.spring.datasource.port}
    dbname: test
    # 连接后缀
    url-other: ?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: ${public.spring.datasource.username}
    password: ${public.spring.datasource.password}
